title: FromOopsToOps
tagline: DevOps & Cloud Engineer — turning chaos into ops
description: DevOps & Cloud engineering, reliability, cost optimization, and automation.
url: https://odinops.github.io
author:
  name: Rafael Umbelino
  links:
    linkedin: https://linkedin.com/in/rafaelumb
    github: https://github.com/FromOopsToOps
    medium: https://medium.com/@fromoopstoops
    telegram: https://t.me/odinUmbelino
    whatsapp: https://wa.me/+5548998142779
theme: null
remote_theme: JustGoodThemes/BlogBox-Jekyll-Theme
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
markdown: kramdown
kramdown:
  input: GFM
permalink: /:title/
collections:
  projects:
    output: true
defaults:
  - scope: { path: "" }
    values:
      layout: default
  - scope: { path: "", type: "posts" }
    values:
      layout: post
  - scope: { path: "", type: "projects" }
    values:
      layout: page

